#include "hardware/pio.h"
#include "pico/stdlib.h"
#include "tusb.h"

// This header is automatically generated by CMake from the ws2812.pio file
#include "ws2812.pio.h"

#define JIGGLE_INTERVAL_MS 10000 // 60 seconds
#define LED_PIN 16
#define BLINK_INTERVAL_MS 500 // blink speed (500ms ON, 500ms OFF)

static bool led_state = false;
static uint32_t last_blink_time = 0;

// globals
bool enabled = true;
bool left_right = true;
uint16_t duration_sec = 60;
uint16_t pixels = 1;
uint8_t targeted_workspace = 7;
uint8_t led_control = 0;

#define PIO_BLOCK pio0
#define SM_NUM 0

// Helper to send a 24-bit GRB color to the PIO FIFO queue
static inline void set_neopixel_color(uint8_t r, uint8_t g, uint8_t b) {
  // WS2812 expects data in MSB-first format: Green, then Red, then Blue
  uint32_t grb_color =
      ((uint32_t)(g) << 16) | ((uint32_t)(r) << 8) | ((uint32_t)(b));

  // Shift up to the top 24 bits because the PIO program reads from the MSB side
  pio_sm_put_blocking(PIO_BLOCK, SM_NUM, grb_color << 8u);
}

// Handles the non-blocking blink timing
void led_blink_task(void) {
  uint32_t current_time = to_ms_since_boot(get_absolute_time());

  // Check if enough time has passed
  if (current_time - last_blink_time >= BLINK_INTERVAL_MS) {
    last_blink_time = current_time;
    led_state = !led_state; // Toggle the state

    if (led_state) {
      if (led_control & 0x04) {
        set_neopixel_color(255, 0, 0); // Red on
        led_control = (led_control & ~(1U << 2)) | (1U << 3);
      } else if (led_control & 0x08) {
        set_neopixel_color(0, 255, 0); // Green on
        led_control = (led_control & ~(1U << 3)) | (1U << 4);
      } else if (led_control & 0x10) {
        set_neopixel_color(0, 0, 255); // Blue on
        led_control = (led_control & ~(1U << 4)) | (1U << 2);
      }
    } else {
      set_neopixel_color(0, 0, 0); // off
    }
  }
}

void mouse_jiggle_task(void) {
  static uint32_t start_ms = 0;
  static bool direction = false;

  // check if the USB host is ready and configured
  if (!tud_hid_ready())
    return;

  uint32_t current_time_ms = to_ms_since_boot(get_absolute_time());

  // move mouse run when interval expires
  if (current_time_ms - start_ms < JIGGLE_INTERVAL_MS)
    return;

  start_ms = current_time_ms;

  if (direction) {
    // right 1 pixel
    tud_hid_mouse_report(1, 0, 10, 0, 0, 0);
  } else {
    // left 1 pixel
    tud_hid_mouse_report(1, 0, -10, 0, 0, 0);
  }

  // toggle direction for the next run
  direction = !direction;
}

/*
void tud_mount_cb() {
  set_neopixel_color(0, 255, 0);
}
*/

int main(void) {
  stdio_init_all();

  uint offset = pio_add_program(PIO_BLOCK, &ws2812_program);
  ws2812_program_init(PIO_BLOCK, SM_NUM, offset, LED_PIN, 800000, false);

  set_neopixel_color(0, 0, 0);

  tusb_init();

  led_control = 0x04;

  while (1) {
    tud_task(); // TinyUSB device task
    mouse_jiggle_task();
    led_blink_task();
  }
}

/*
// TinyUSB callback triggered when the host sends data over CDC (Serial)
void tud_cdc_rx_cb(uint8_t itf) {
    // Toggle or turn on the LED to show activity
    gpio_put(LED_PIN, 1);

    // Read and handle the data...
    uint8_t buf[64];
    uint32_t count = tud_cdc_n_read(itf, buf, sizeof(buf));

    // (Optional) Turn it right back off, or off in your main loop after a delay
    // gpio_put(LED_PIN, 0);
}
*/

/*
// callback when device is mounted and connected
void tud_mount_cb() {
   gpio_put(LED_PIN, 1);
}
*/

// Required TinyUSB callbacks
uint16_t tud_hid_get_report_cb(uint8_t instance, uint8_t report_id,
                               hid_report_type_t report_type, uint8_t *buffer,
                               uint16_t reqlen) {
  (void)instance;
  (void)report_id;
  (void)report_type;
  (void)buffer;
  (void)reqlen;
  return 0;
}

void tud_hid_set_report_cb(uint8_t instance, uint8_t report_id,
                           hid_report_type_t report_type, uint8_t const *buffer,
                           uint16_t bufsize) {
  (void)instance;
  (void)report_id;
  (void)report_type;
  (void)buffer;
  (void)bufsize;
}
